function aaSeqs = translate_nt(ntSeqs)
% TRANSLATE_NT Translate multiple nucleotide sequences into amino acid sequences.
%
%   aaSeqs = translate_nt(ntSeqs)
%
%   Input:
%       ntSeqs - character matrix where each row is one nucleotide sequence
%
%   Output:
%       aaSeqs - character matrix where each row is the corresponding
%                amino acid sequence using one-letter amino acid codes
%
%   Stop codons are represented by '*'.
%
%   Example:
%       ntSeqs = ['ATGGCTTAA';
%                 'ATGCCCTGA'];
%
%       aaSeqs = translate_nt(ntSeqs)
%
%       % returns:
%       % 'MA*'
%       % 'MP*'

    % Convert to uppercase character array
    ntSeqs = upper(char(ntSeqs));

    % Get dimensions
    [nSeqs, nNt] = size(ntSeqs);

    % Check for valid nucleotides
    if any(~ismember(ntSeqs(:), 'ACGT'))
        error('Sequences contain characters other than A, C, G, or T.');
    end

    % Check that sequence length contains complete codons
    if mod(nNt, 3) ~= 0
        error('Nucleotide sequence length must be a multiple of 3.');
    end

    % Standard genetic code
    codons = { ...
        'TTT','TTC','TTA','TTG', ...
        'TCT','TCC','TCA','TCG', ...
        'TAT','TAC','TAA','TAG', ...
        'TGT','TGC','TGA','TGG', ...
        'CTT','CTC','CTA','CTG', ...
        'CCT','CCC','CCA','CCG', ...
        'CAT','CAC','CAA','CAG', ...
        'CGT','CGC','CGA','CGG', ...
        'ATT','ATC','ATA','ATG', ...
        'ACT','ACC','ACA','ACG', ...
        'AAT','AAC','AAA','AAG', ...
        'AGT','AGC','AGA','AGG', ...
        'GTT','GTC','GTA','GTG', ...
        'GCT','GCC','GCA','GCG', ...
        'GAT','GAC','GAA','GAG', ...
        'GGT','GGC','GGA','GGG'};

    aminoAcids = [ ...
        'FFLL' ...
        'SSSS' ...
        'YY**' ...
        'CC*W' ...
        'LLLL' ...
        'PPPP' ...
        'HHQQ' ...
        'RRRR' ...
        'IIIM' ...
        'TTTT' ...
        'NNKK' ...
        'SSRR' ...
        'VVVV' ...
        'AAAA' ...
        'DDEE' ...
        'GGGG'];

    % Create codon lookup table
    geneticCode = containers.Map(codons, cellstr(aminoAcids(:)));

    % Number of amino acids per sequence
    nCodons = nNt / 3;

    % Preallocate output
    aaSeqs = repmat(' ', nSeqs, nCodons);

    % Translate each sequence
    for seq = 1:nSeqs
        for i = 1:nCodons

            idx = (i - 1) * 3 + 1;
            codon = ntSeqs(seq, idx:idx+2);

            aaSeqs(seq, i) = geneticCode(codon);

        end
    end

end